name: Push to Specified Branches

on:
  push:
    branches:
      - master

jobs:
  push_to_specified_branches:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branches:
          - pesfalan
          - naturisa
          - eguiguren
          - acuarios
          - chongon
          # Agrega más ramas aquí según sea necesario
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List branches
        run: git branch -a

      - name: Create and push to specified branches
        run: |
          for branch in "${{ matrix.branches }}"; do
            git checkout -B $branch origin/$branch || git checkout -b $branch
            git push --force origin $branch
          done