name: Sync Branches

on:
  push:
    branches:
      - master  # Reemplaza "main" con la rama de origen de tu elección

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source branch
      uses: actions/checkout@v4
      with:
        ref: master  # Reemplaza "main" con la rama de origen de tu elección

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Fetch all branches
      run: |
        git fetch --all

    - name: Sync branches
      run: |
        # Lista de ramas a las que quieres hacer push
        branches_to_sync="eguiguren naturisa pesfalan"
        for branch in $branches_to_sync; do
          git checkout $branch || git checkout -b $branch
          git merge main --no-edit
          git push origin $branch
        done
