name: Update branches on push to master

on:
  push:
    branches:
      - master

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create and update branches
        run: |
          BRANCHES=("branch1" "branch2" "branch3")  # Lista de ramas a actualizar
          for branch in "${BRANCHES[@]}"; do
            git checkout -B $branch  # Crear la rama si no existe, o reescribir si existe
            git push origin $branch --force-with-lease
          done
