name: Update projections

on:
  push:
    branches:
      - master

jobs:
  update-branches:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [eguigurenv2, naturisav2, pesfalanv2]  # Lista de ramas que deseas actualizar

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git config --global credential.helper '!f() { echo "username=github-actions"; echo "password=${ACTIONS_PAT}"; }; f'

      - name: Fetch all branches
        run: git fetch --all
      
      - name: Pull latest changes from master
        run: git pull origin master

      - name: Check if branch exists
        id: check_branch
        run: |
          if git rev-parse --verify --quiet ${{ matrix.branch }}; then
            echo "::set-output name=branch_exists::true"
          else
            echo "::set-output name=branch_exists::false"
          fi

      - name: Create branch if it doesn't exist
        if: steps.check_branch.outputs.branch_exists == 'false'
        run: |
          git checkout -b ${{ matrix.branch }}
          git pull origin master
          git push origin ${{ matrix.branch }}

      - name: Update branch
        if: steps.check_branch.outputs.branch_exists == 'true'
        run: |
          git checkout ${{ matrix.branch }}
          git merge master
          git push origin ${{ matrix.branch }}